env:
  es2021: true
  node: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - prettier

parserOptions:
  project:
    - tsconfig.eslint.json
  sourceType: module
  ecmaVersion: latest

rules:
  "@typescript-eslint/explicit-module-boundary-types": warn
  "@typescript-eslint/no-unused-vars":
    - warn
    - varsIgnorePattern: "^_"
      args: none
      ignoreRestSiblings: true
  "@typescript-eslint/no-non-null-assertion": off
  "@typescript-eslint/consistent-type-imports": error

ignorePatterns:
  - "demo/usage.ts"
